language: node_js
cache:
  yarn: false
  npm: false
script:
  - yarn lint && yarn test
notifications:
  email:
    recipients:
      - martin.salias@kleer.la
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: zu1OM+Zzh9WUpVJ8mShk/A92YFx1gJ8LxIUizRSxTZw+SUCXKPSAcLOD4ZsA1EMbQSxLMQx11J76VOXT/A/lcceEpDroA37hdcipjyM0EsaYo+g6ZnastVIU/uI4jxKEa37gBXbdasgCq+fXyGJ+6x244owtqrJ0/cWqdp7+0w+sSOH6XI4yg6carBmSjNNsQYACjLkOnLNpmtPEdx12tDFFks66zyV58gIvBEDU/klduuyqsZLJBYp9t8hfMtdS85DEdA8HUsYPIeahce+B5iyJYkOzvcnHAylz87DZPElKogEIwgPJXdbxyQofTL5FZhTmDVPLN+jTbbaKTKXcgRfscbIN4mBIFhHuXs4hi4IJ5jlO5BXpZEIK44Q5JuF5rfszYs8mv0fiZzn7mUslAhxxFWZmUS08hW7ECAuF4QXpDVIN8Vz+3IQ9ZJCAoRB/PUlK83VO9FjhxXPi+MrABLetUrr0FCiVclNhbIE+eDTmB9FYNH0/p+YWq4KYzUda/46IMpbdK2Jse5uuRZYeDhd8w+L5mMW++Ei0+PPRMJfBntRKGqKNzLLN2EKIPuUmLMWkMj2TBSWF94AoGyGRdsdHDmMxS3qYY/xhcXsac7NZPx2Gw3PKwdBV9z3lbWzcywZPEuJwz64o3XE/aO5jFsgsP2iKltdNKrUSSUTTeRo=
    app: nahual-portal-voluntaries
    on:
      branch: production
      repo: taller-de-desarrollo-proyectos-III/front-end
